#!/bin/sh

# Prompt
local smiley="%(?,%{$fg[green]%}☺%{$reset_color%},%{$fg[red]%}☹%{$reset_color%})"

PROMPT='
$(display-rails-env)%{$terminfo[bold]%}%{$fg[black]%}$(whoami)@$(hostname)%{$reset_color%} %~
${smiley}  %{$reset_color%}'

RPROMPT='%{$fg[black]%} $(~/.rvm/bin/rvm-prompt)$(~/bin/git-cwd-info.rb)%{$reset_color%}'

