---
- hosts: all
  vars:
    packages:
      - curl
      - git
      - rbenv
      - ruby-build
      - vim
      - wget
  roles:
  - role: osx
    when: ansible_distribution == 'MacOSX'
  - role: ubuntu
    when: ansible_distribution == 'Ubuntu'

  tasks:
  - name: symlink dotfiles and dotdirectories
    file: dest=~/.{{item}}
          src=~/.dotfiles/files/{{item}}
          state=link
          force=true
    with_items:
    - aliases
    - bash_completion.d
    - bash_profile
    - bashrc
    - gemrc
    - gitconfig
    - gitignore_global
    - gvimrc
    - inputrc
    - irbrc
    - lessfilter
    - path
    - profile
    - pryrc
    - rspec
    - tmux.conf
    - vim
    - vimrc

  - name: setup vundle
    git: repo=https://github.com/gmarik/Vundle.vim.git
         dest=~/.vim/bundle/Vundle.vim

  - name: install vundle bundles
    shell: vim +PluginInstall +qall
