#!/bin/bash

has_stow() {
  if [ ! -f "$(which stow)" ]; then
    echo 'Please install stow.'
    echo '  See http://www.gnu.org/software/stow/'
    echo ''
    echo '  To install:'
    case "$(uname)" in
      "Darwin")
        echo '  brew install stow'
        ;;
      "Linux")
        echo ' apt-get install stow'
        ;;
    esac
    exit 1
  fi
  return 0
}

has_stow

for package in bash git ruby vim
do
  stow --verbose --target="$HOME" $package
done

# Setup Vim
[ ! -d ~/.vim/bundle/vundle ] && git clone https://github.com/gmarik/vundle.git /.vim/bundle/vundle
vim +BundleInstall +qall

echo 'Installation complete'
