#!/bin/bash
# Shamelessly copied from https://github.com/gf3/dotfiles
# Screenshot: http://i.imgur.com/s0Blh.png

if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
  export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
  export TERM=xterm-256color
fi

if tput setaf 1 &> /dev/null; then
  tput sgr0
  if [[ $(tput colors) -ge 256 ]] 2>/dev/null; then
    MAGENTA=$(tput setaf 9)
    ORANGE=$(tput setaf 172)
    GREEN=$(tput setaf 190)
    PURPLE=$(tput setaf 141)
    WHITE=$(tput setaf 0)
    BLUE=$(tput setaf 69)
  else
    MAGENTA=$(tput setaf 5)
    ORANGE=$(tput setaf 4)
    GREEN=$(tput setaf 2)
    PURPLE=$(tput setaf 1)
    WHITE=$(tput setaf 7)
    BLUE=$(tput setaf 12)
  fi
  BOLD=$(tput bold)
  RESET=$(tput sgr0)
else
  MAGENTA="\033[1;31m"
  ORANGE="\033[1;33m"
  GREEN="\033[1;32m"
  PURPLE="\033[1;35m"
  WHITE="\033[1;37m"
  BOLD=""
  RESET="\033[m"
  BLUE="\033[1;69m"
fi

export MAGENTA
export ORANGE
export GREEN
export PURPLE
export WHITE
export BLUE
export BOLD
export RESET

function color_swatches() {
  for i in {0..256}; do
    echo -en "\e[38;5;${i}m$i \e[0m";
  done;
  echo
}

function parse_git_dirty() {
  [[ $(git status 2> /dev/null | tail -n1) != *"working directory clean"* ]] && echo "*"
}

function parse_git_branch() {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
}

function ruby_version_prompt() {
  local ruby_version=$(ruby -v | awk '{ print $2 }')
  RUBY_PROMPT=" ${WHITE}${BOLD}w/ rb ${MAGENTA}${ruby_version}"
  PS1="$PS1$RUBY_PROMPT"
}

function user_prompt() {
  PS1="$PS1${BLUE}\u"
}

function host_prompt() {
  PS1="$PS1 \[$WHITE\]at \[$ORANGE\]\h"
}

function git_prompt() {
  PS1="$PS1\[$WHITE\]\$([[ -n \$(git branch 2> /dev/null) ]] && echo \" on \")\[$PURPLE\]\$(parse_git_branch)"
}

function pwd_prompt() {
  PS1="$PS1 \[$WHITE\]in \[$GREEN\]\w"
}

function last_command_prompt() {
  PS1="$PS1 \[$WHITE\]\n\$ \[$RESET\]"
}

function prompt(){
  PS1="${BOLD}"
  user_prompt
  host_prompt
  pwd_prompt
  git_prompt
  ruby_version_prompt
  last_command_prompt
  export PS1
}
export PS2="\[$ORANGE\]→ \[$RESET\]"
export PROMPT_COMMAND=prompt


