---

# test homebrew
# ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#
- name: install brew packages
  homebrew: name={{item}}
            state=latest
  with_items: packages | union(osx_additional_packages)

- name: test for brew cask
  shell: brew cask
  register: cask_installed
  ignore_errors: yes

- name: install brew cask
  shell: brew install caskroom/cask/brew-cask
  sudo: yes
  when: cask_installed | failed

- name: install applications
  shell: brew cask install {{item}}
  with_items: osx_applications
  register: cask_install
  changed_when: cask_install.stderr.find('installed to') != -1
