" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set guifont=Monaco:h12            " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set background=light              " Background.
set lines=25 columns=100          " Window dimensions.

set guioptions-=r                 " Don't show right scrollbar

set t_Co=256
colorscheme twilight
set transparency=10


" Use Jamis Buck's file opening plugin FuzzyFinder
map <leader>t :FuzzyFinderTextMate<Enter>
map <leader><S-t> :FuzzyFinderTag<Enter>
map <leader>b :FuzzyFinderBuffer<Enter>
map <leader>] :FuzzyFinderMruFile<Enter>
let g:fuzzy_ceiling=25000
let g:fuzzy_ignore=".git/**/*;.svn/**/*;*.gif;*.png;*.jpg;*.log;tmp/**/*"

