
set nocompatible                  " Must come first because it changes other options.

silent! call pathogen#runtime_append_all_bundles()

syntax on

set directory=$HOME/.vimtmp//,.  " Keep swap files in one location

nnoremap <leader>d :NERDTreeToggle<Enter> 

