set nocompatible                  " Must come first because it changes other options.

if filereadable(expand("~/.vim/vundles.vim"))
  source ~/.vim/vundles.vim
endif

set visualbell                    " No beeping.
set history=1000                  " Store a lot of history
set number                        " Turn on line numbers
set tabstop=2                     " Global tab width.
set shiftwidth=2                  " And again, related.
set expandtab                     " Use spaces instead of tabs
set smarttab                      " sw at start of line, sts everywhere else
set autoread                      " Reload files changed outside vim
set autoindent

set exrc            " enable per-directory .vimrc files
set secure          " disable unsafe commands in local .vimrc files

syntax on             " Enable syntax highlighting
filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific plugins

set directory=$HOME/.vimtmp//,.  " Keep swap files in one location

set laststatus=2                  " Show the status line all the time

set t_Co=256
set background=dark
colorscheme Tomorrow-Night
