#!/bin/sh

create_temp_dir(){
  if [ ! -d "$HOME/tmp" ]; then
    echo "Making temporary directory."
    mkdir -p "$HOME/tmp"
    cd "$HOME/tmp"
  fi
}

install_basic_packages() {
  sudo apt-get install git vim curl -y
}

install_google_chrome() {
  which google-chrome > /dev/null
  if [ "$?" -ne "0" ]; then
    echo "Installing Google Chrome."
    sudo apt-get install libxss1
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo dpkg -i google-chrome-stable_current_amd64.deb -y
    rm google-chrome-stable_current_amd64.deb
  else
    echo "Google Chrome already installed."
  fi
}

setup_keyboard() {
  grep ctrl:nocaps /etc/default/keyboard > /dev/null
  if [ "$?" -ne "0" ]; then
    echo "Making Capslock the CTRL key. You will need to log out and back in for this to work."
    sudo sed -i s/^XKBOPTIONS=\".*\"/XKBOPTIONS=\"ctrl:nocaps\"/ /etc/default/keyboard
  fi
}

setup_dotfiles() {
  if [ ! -d "$HOME/source/dotfiles" ]; then
    echo "Cloning dotfiles from Github via HTTPS. Change origin remote after SSH keys all setup"
    [ !-d "$HOME/source" ] && mkdir -p $HOME/source
    git clone https://github.com/MarkBorcherding/dotfiles.git $HOME/source/dotfiles
    sudo apt-get install stow
    cd $HOME/source/dotfiles
    ./install
  fi
}


create_temp_dir
install_basic_packages
install_google_chrome
setup_keyboard
setup_dotfiles
../setup_sshkeys
./setup-git-keystore

