#!/bin/sh

setup-git-keystore() {
  sudo apt-get install libgnome-keyring-dev --yes
  cd /usr/share/doc/git/contrib/credential/gnome-keyring
  sudo make
  git config --global credential.helper /usr/share/doc/git/contrib/credential/gnome-keyring/git-credential-gnome-keyring
}

setup-git-keystore
