# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#export ZSH_THEME="pmcgee"
#export ZSH_THEME="agnoster"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# export DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-remove-branch rails3 ruby rvm brew github osx gem bundler heroku node npm textmate pow vagrant sublime pip vi-mode colored-man bower)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
alias ls="ls -G"

export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=1
export LSCOLORS=ExGxFxDxCxHxHxCbCeEbEb
unsetopt auto_name_dirs

# Multiple Move
# example:  mmv *.data *.backup_data
autoload -U zmv
alias mmv='noglob zmv -W'

# Paths
export NODE_PATH="/usr/local/lib/node:/usr/local/lib/node_modules"


PATH="$HOME/pear/bin:$PATH"                       # Pear bins
PATH="./node_modules/.bin:$PATH"                  # Add the local node modules bins
PATH="/usr/local/share/npm/bin:$PATH"             # Add the global npm bins to the path
PATH="/usr/local/bin:/usr/local/sbin:$PATH"       # Add to keep brew happy
PATH="/usr/local/heroku/bin:$PATH"                # Added by the Heroku Toolbelt
PATH="$HOME/.rvm/bin:$PATH"                       # Add RVM to PATH for scripting
PATH="$HOME/bin:$PATH"                            # My additional bins
PATH="/Applications/Postgres.app/Contents/MacOS/bin:$PATH" # Add Postgres.app to the path
PATH="/usr/local/lib/python2.7/site-packages:$PATH"        # Add Python packages to path
export PATH

# Colors
if [ -e /usr/share/terminfo/x/xterm-256color ]; then
  export TERM='xterm-256color'
else
  export TERM='xterm-color'
fi
autoload -U colors
colors
setopt prompt_subst

# Turn off the spelling correct.
unsetopt correct_all


# Prompt
local smiley="%(?,%{$fg[green]%}☺%{$reset_color%},%{$fg[red]%}☹%{$reset_color%})"

PROMPT='
$(display-rails-env)%{$terminfo[bold]%}%{$fg[black]%}$(whoami)@$(hostname)%{$reset_color%} %~
${smiley}  %{$reset_color%}'

RPROMPT='%{$fg[black]%} $(~/.rvm/bin/rvm-prompt)$(~/bin/git-cwd-info.rb)%{$reset_color%}'

# Show completion on first TAB
setopt menucomplete

# # Load completions for Ruby, Git, etc.
autoload compinit
compinit

# RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.
[[ -s $HOME/.pythonbrew/etc/bashrc ]] && source $HOME/.pythonbrew/etc/bashrc

[[ -s $HOME/.secrets ]] && source $HOME/.secrets

